[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project]
name = "portcraft"
description = "A simple CICD tool"
readme = "README.md"
keywords = ["cicd", "automation", "tools"]
version = "1.0.0"

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
